# Generated by Django 4.2.1 on 2023-05-20 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Alunos',
                'db_table': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('id_area_conhecimento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Áreas do Conhecimento',
                'db_table': 'AreaConhecimento',
            },
        ),
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id_conta', models.AutoField(primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=255)),
                ('agencia', models.CharField(max_length=8)),
                ('conta', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('C', 'Corrente'), ('P', 'Poupança')], default='C', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Contas',
                'db_table': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='HorariosTutor',
            fields=[
                ('id_horario_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Horários dos Tutores',
                'db_table': 'HorariosTutor',
            },
        ),
        migrations.CreateModel(
            name='Tutores',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.contas')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tutores',
                'db_table': 'Tutores',
            },
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id_tutoria', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('link', models.URLField()),
                ('status', models.CharField(choices=[('A', 'Agendada'), ('C', 'Cancelada'), ('F', 'Finalizada')], default='A', max_length=1)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.alunos')),
                ('id_horario_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.horariostutor')),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.tutores')),
            ],
            options={
                'verbose_name_plural': 'Tutorias',
                'db_table': 'Tutoria',
            },
        ),
        migrations.CreateModel(
            name='SubareasConhecimento',
            fields=[
                ('id_sub_area_conhecimento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('id_area_conhecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.areaconhecimento')),
            ],
            options={
                'verbose_name_plural': 'Subáreas do Conhecimento',
                'db_table': 'SubareasConhecimento',
            },
        ),
        migrations.CreateModel(
            name='InteresseAluno',
            fields=[
                ('id_interesse_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.alunos')),
                ('id_sub_area_conhecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.subareasconhecimento')),
            ],
            options={
                'verbose_name_plural': 'Interesses dos Alunos',
                'db_table': 'InteresseAluno',
            },
        ),
        migrations.AddField(
            model_name='horariostutor',
            name='id_tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.tutores'),
        ),
        migrations.CreateModel(
            name='EspecializacaoTutor',
            fields=[
                ('id_especializacao_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('comprovante', models.FileField(upload_to='comprovantes/')),
                ('valor', models.FloatField()),
                ('descricao', models.TextField()),
                ('id_sub_area_conhecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.subareasconhecimento')),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.tutores')),
            ],
            options={
                'verbose_name_plural': 'Especializações dos Tutores',
                'db_table': 'EspecializacaoTutor',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoTutor',
            fields=[
                ('id_avaliacao_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.PositiveIntegerField()),
                ('comentario', models.TextField()),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.alunos')),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.tutores')),
            ],
            options={
                'verbose_name_plural': 'Avaliações dos Tutores',
                'db_table': 'AvaliacaoTutor',
            },
        ),
    ]
