# Generated by Django 4.2.1 on 2023-05-20 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brotherInCode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='id_sub_area_conhecimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.subareasconhecimento'),
        ),
    ]
