# Generated by Django 4.2.1 on 2023-05-20 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brotherInCode', '0002_tutoria_id_sub_area_conhecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especializacaotutor',
            name='comprovante',
        ),
        migrations.AddField(
            model_name='alunos',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='id_sub_area_conhecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.subareasconhecimento'),
        ),
        migrations.CreateModel(
            name='ComprovantePagamento',
            fields=[
                ('id_comprovante_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('comprovante', models.FileField(upload_to='comprovantes/pagamento/')),
                ('id_tutoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.tutoria')),
            ],
            options={
                'verbose_name_plural': 'Comprovantes de Pagamento',
                'db_table': 'ComprovantePagamento',
            },
        ),
        migrations.CreateModel(
            name='ComprovanteEspecializacao',
            fields=[
                ('id_comprovante_especializacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('D', 'Diploma'), ('C', 'Certificado'), ('O', 'Outros')], max_length=1)),
                ('comprovante', models.FileField(upload_to='comprovantes/especializacao/')),
                ('id_especializacao_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brotherInCode.especializacaotutor')),
            ],
            options={
                'verbose_name_plural': 'Comprovantes de Especialização',
                'db_table': 'ComprovanteEspecializacao',
            },
        ),
    ]
