# Generated by Django 4.2.1 on 2023-05-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brotherInCode', '0003_remove_especializacaotutor_comprovante_alunos_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
